
"""
mediumapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class MiscControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.misc
        cls.response_catcher = cls.controller.http_call_back

    def test_get_latest_posts(self):
        """
        Returns a list of latest posts (`article_ids`) for a topic/niche (as
        classified by the Medium platform). Example of a topic/niche can be:*
        blockchain* relationships* mental-health, etc …These are known as
        `topic_slugs`. At any given moment, this endpoint will return a list of 25
        articles (`article_ids`)..
        """
        # Parameters for the API call
        topic_slug = "artificial-intelligence"

        # Perform the API call through the SDK function
        self.controller.get_latest_posts(
            topic_slug,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_related_tags(self):
        """
        Returns a list of `related_tags` for the given `tag`..
        """
        # Parameters for the API call
        tag = "blockchain"

        # Perform the API call through the SDK function
        self.controller.get_related_tags(
            tag,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_top_writers(self):
        """
        Returns a list of top writers (`user_ids`) within a particular topic/niche
        (`topic_slug`). e.g. - blockchain- relationships- artificial-intelligence, etc
        ...**Note:** You can use optional `count` query parameter to limit the number
        of results.  The maximum number of top writers within a topic/niche will be
        250..
        """
        # Parameters for the API call
        topic_slug = "relationships"
        count = 10

        # Perform the API call through the SDK function
        self.controller.get_top_writers(
            topic_slug,
            count,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_topfeeds(self):
        """
        Returns a list of `article_ids` (length: 25) for the given `tag` and `mode`..
        """
        # Parameters for the API call
        tag = "artificial-intelligence"
        mode = "new"
        after = 0
        count = 25

        # Perform the API call through the SDK function
        self.controller.get_topfeeds(
            tag,
            mode,
            after,
            count,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

