
"""
mediumapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class PublicationControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.publication
        cls.response_catcher = cls.controller.http_call_back

    def test_get_publication_id(self):
        """
        Returns the unique `publication_id` for the given `publication_slug`.**Note:**
        You can find the `publication_slug` from the publication's homepage URL.-
        medium.com/**publication_slug**.
        """
        # Parameters for the API call
        publication_slug = "codex"

        # Perform the API call through the SDK function
        self.controller.get_publication_id(
            publication_slug,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_publication_info(self):
        """
        Returns the publication related information such as *Publication name,
        Tagline, Description, Tags, Followers Count, Twitter username, Instagram
        username, Facebook Page name, etc …***Note:** If you don't know the
        `publication_id`, you can get it from any article published by it. Use
        endpoint "/article/{article_id}" to retrieve the `publication_id`..
        """
        # Parameters for the API call
        publication_id = "98111c9905da"

        # Perform the API call through the SDK function
        self.controller.get_publication_info(
            publication_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_publication_articles(self):
        """
        Returns the list of `articles_ids`, of the latest 25 articles, posted in that
        publication..
        """
        # Parameters for the API call
        publication_id = "98111c9905da"
        mfrom = "2023-01-31T13:10:00"

        # Perform the API call through the SDK function
        self.controller.get_publication_articles(
            publication_id,
            mfrom,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_publication_newsletter(self):
        """
        Returns the newsletter related information such as *id, name, description,
        slug, creator_id, subscribers, image_url, etc …***Note:** If you don't know
        the `publication_id`, you can get it from any article published by it. Use
        endpoint "/article/{article_id}" to retrieve the `publication_id`..
        """
        # Parameters for the API call
        publication_id = "98111c9905da"

        # Perform the API call through the SDK function
        self.controller.get_publication_newsletter(
            publication_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

