
"""
mediumapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class SearchControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.search
        cls.response_catcher = cls.controller.http_call_back

    def test_search_articles(self):
        """
        Returns the list of `articles_ids` for the given search query results. (Max
        Length = 1000).
        """
        # Parameters for the API call
        query = "startup"

        # Perform the API call through the SDK function
        self.controller.search_articles(
            query,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_search_lists(self):
        """
        Returns an array of `list_ids` for the given search query results. (Max Length
        = 1000).
        """
        # Parameters for the API call
        query = "artificial intelligence"

        # Perform the API call through the SDK function
        self.controller.search_lists(
            query,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_search_publications(self):
        """
        Returns the list of `publication_ids` for the given search query results. (Max
        Length = 1000).
        """
        # Parameters for the API call
        query = "mental health"

        # Perform the API call through the SDK function
        self.controller.search_publications(
            query,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_search_tags(self):
        """
        Returns a list of `tags` for the given search query results. (Max Length =
        1000).
        """
        # Parameters for the API call
        query = "blockchain"

        # Perform the API call through the SDK function
        self.controller.search_tags(
            query,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_search_users(self):
        """
        Returns a list of `user_ids` for the given search query results. (Max Length =
        1000).
        """
        # Parameters for the API call
        query = "data engineer"

        # Perform the API call through the SDK function
        self.controller.search_users(
            query,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

