
"""
mediumapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class ArticleControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.article
        cls.response_catcher = cls.controller.http_call_back

    def test_get_article_info(self):
        """
        Returns the article related information such as *Title, Subtitle, Tags, 
        Topics* (assigned by Medium), *Publication, Published date and time,  Clap
        Count, Voter Count, Word Count, Reading Time, Language, etc…*.
        """
        # Parameters for the API call
        article_id = "f06086080568"

        # Perform the API call through the SDK function
        self.controller.get_article_info(
            article_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_article_s_content(self):
        """
        Returns the content of an article/story, for the corresponding `article_id`.
        """
        # Parameters for the API call
        article_id = "562c5821b5f0"

        # Perform the API call through the SDK function
        self.controller.get_article_s_content(
            article_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_article_fans(self):
        """
        Returns a list of `user_ids` of the people who clapped on the article (a.k.a
        `voters`)..
        """
        # Parameters for the API call
        article_id = "67fa62fc1971"

        # Perform the API call through the SDK function
        self.controller.get_article_fans(
            article_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_article_s_markdown(self):
        """
        Returns the markdown of an article/story from Medium, for the corresponding
        `article_id`.
        """
        # Parameters for the API call
        article_id = "67fa62fc1971"

        # Perform the API call through the SDK function
        self.controller.get_article_s_markdown(
            article_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_related_articles(self):
        """
        Returns a list of `article_ids` of the related posts. (Length = 5)**Note:** If
        the given article is self-published, related posts will belong to the same
        author,  else related posts will belong to the publication in which the
        article is published..
        """
        # Parameters for the API call
        article_id = "67fa62fc1971"

        # Perform the API call through the SDK function
        self.controller.get_related_articles(
            article_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_article_responses(self):
        """
        Returns a list of responses (`response_ids`, same as `article_ids`) for a
        given article (`article_id`)Note: To see the content of the response, use the
        "Get Article's Content" endpoint.
        """
        # Parameters for the API call
        article_id = "67fa62fc1971"

        # Perform the API call through the SDK function
        self.controller.get_article_responses(
            article_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

