
"""
mediumapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class UserControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.user
        cls.response_catcher = cls.controller.http_call_back

    def test_get_user_id(self):
        """
        Returns the unique `user_id` for the given `username`.**Note:** You can find
        the `username` from the user's/author's profile page URL. -
        **username**.medium.com- medium.com/@**username**.
        """
        # Parameters for the API call
        username = "nishu-jain"

        # Perform the API call through the SDK function
        self.controller.get_user_id(
            username,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_user_info(self):
        """
        Returns user related information like *Full name, Bio, Followers count,
        Following count, Twitter username, Profile-image URL, User ID, etc...* It
        takes `user_id` as the path parameter.**Note:** If you don't know the
        `user_id`, then you can get it from the endpoint\'/user/id_for/{`username`}'..
        """
        # Parameters for the API call
        user_id = "1985b61817c3"

        # Perform the API call through the SDK function
        self.controller.get_user_info(
            user_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_user_s_articles(self):
        """
        Returns the list of articles (`article_ids`) written by the user..
        """
        # Parameters for the API call
        user_id = "1985b61817c3"

        # Perform the API call through the SDK function
        self.controller.get_user_s_articles(
            user_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_user_followers(self):
        """
        Returns the list of `user_ids` of the user's followers.**Note:** The length of
        this followers' list might be different from what you get in  the "Get User
        Info" Endpoint. It's because, this list doesn't include Medium Users who  left
        the platform.If you really need the exact followers' count, use this endpoint
        to get the followers'  list and take its length as the exact followers' count.
        """
        # Parameters for the API call
        user_id = "1985b61817c3"
        count = 10

        # Perform the API call through the SDK function
        self.controller.get_user_followers(
            user_id,
            count,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_user_following(self):
        """
        Returns the list of `user_ids` of the user's followings.**Note:** Currently,
        this list does not contain the `publication_ids` of the publications that the
        user is following..
        """
        # Parameters for the API call
        user_id = "14d5c41e0264"
        count = 10

        # Perform the API call through the SDK function
        self.controller.get_user_following(
            user_id,
            count,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_user_s_interests(self):
        """
        Returns a list of tags that the given user follows..
        """
        # Parameters for the API call
        user_id = "1985b61817c3"

        # Perform the API call through the SDK function
        self.controller.get_user_s_interests(
            user_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_user_s_lists(self):
        """
        Returns an array of `list_ids` created by the user.**Note:** You can check
        whether the use has created lists or not beforehand. Check the  `has_list`
        attribute in the "Article Info" endpoint..
        """
        # Parameters for the API call
        user_id = "5142451174a3"

        # Perform the API call through the SDK function
        self.controller.get_user_s_lists(
            user_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_user_s_publications(self):
        """
        Returns a list of `publication_ids` where the user is the editor and/or
        creator..
        """
        # Parameters for the API call
        user_id = "14d5c41e0264"

        # Perform the API call through the SDK function
        self.controller.get_user_s_publications(
            user_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_user_s_top_articles(self):
        """
        Returns a list of `article_ids` of the top 10 articles on the user's profile,
        for a given `user_id`..
        """
        # Parameters for the API call
        user_id = "1985b61817c3"

        # Perform the API call through the SDK function
        self.controller.get_user_s_top_articles(
            user_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

