
"""
mediumapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class ListControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.list
        cls.response_catcher = cls.controller.http_call_back

    def test_get_list_info(self):
        """
        Returns the list-related information such as *id, name, author, description, 
        thumbnail image url, creation datetime, last article inserted datetime, 
        number of articles in the list, claps, voters, and comments/responses*..
        """
        # Parameters for the API call
        list_id = "38f9e0f9bea6"

        # Perform the API call through the SDK function
        self.controller.get_list_info(
            list_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_list_articles(self):
        """
        Returns an array of `articles_ids` present in the given Medium List..
        """
        # Parameters for the API call
        list_id = "38f9e0f9bea6"

        # Perform the API call through the SDK function
        self.controller.get_list_articles(
            list_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

    def test_get_list_responses(self):
        """
        Returns an array of `response_ids` of the comments (same as `article_ids`) on
        the given Medium List..
        """
        # Parameters for the API call
        list_id = "38f9e0f9bea6"

        # Perform the API call through the SDK function
        self.controller.get_list_responses(
            list_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )

