"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from mediumapi.configuration import (
    Configuration,
    Environment,
)
from mediumapi.controllers.article_controller import (
    ArticleController,
)
from mediumapi.controllers.base_controller import (
    BaseController,
)
from mediumapi.controllers.list_controller import (
    ListController,
)
from mediumapi.controllers.misc_controller import (
    MiscController,
)
from mediumapi.controllers.publication_controller import (
    PublicationController,
)
from mediumapi.controllers.search_controller import (
    SearchController,
)
from mediumapi.controllers.user_controller import (
    UserController,
)
from mediumapi.controllers.welcome_controller import (
    WelcomeController,
)
from mediumapi.http.auth.api_host import ApiHost
from mediumapi.http.auth.api_key import ApiKey


class MediumapiClient(object):
    """Client that provide access to the MediumapiClient APIs."""

    @LazyProperty
    def welcome(self):
        """Provide access to the WelcomeController endpoints."""
        return WelcomeController(self.global_configuration)

    @LazyProperty
    def user(self):
        """Provide access to the UserController endpoints."""
        return UserController(self.global_configuration)

    @LazyProperty
    def publication(self):
        """Provide access to the PublicationController endpoints."""
        return PublicationController(self.global_configuration)

    @LazyProperty
    def article(self):
        """Provide access to the ArticleController endpoints."""
        return ArticleController(self.global_configuration)

    @LazyProperty
    def misc(self):
        """Provide access to the MiscController endpoints."""
        return MiscController(self.global_configuration)

    @LazyProperty
    def list(self):
        """Provide access to the ListController endpoints."""
        return ListController(self.global_configuration)

    @LazyProperty
    def search(self):
        """Provide access to the SearchController endpoints."""
        return SearchController(self.global_configuration)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 environment=Environment.PRODUCTION, api_host_credentials=None,
                 api_key_credentials=None, config=None):
        """Initialize a new instance of MediumapiClient."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings, environment=environment,
            api_host_credentials=api_host_credentials,
            api_key_credentials=api_key_credentials)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseController.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseController.user_agent(),
                BaseController.user_agent_parameters())

        self.auth_managers = {
            "ApiHost": ApiHost(self.config.api_host_credentials),
            "ApiKey": ApiKey(self.config.api_key_credentials),
        }
        self.global_configuration =\
            self.global_configuration.auth_managers(self.auth_managers)

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            MediumapiClient instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
