
"""
mediumapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os

from apimatic_core.authentication.header_auth import HeaderAuth


class ApiKey(HeaderAuth):
    """
    An authentication handler that applies `CustomHeaderAuthentication` to
    outgoing requests. It constructs the required credential values and integrates
    with the core authentication framework.
    """

    @property
    def error_message(self):
        """Return reason about the authentication failure."""
        return "ApiKey: x_rapidapi_key is undefined."

    def __init__(self, auth_model):
        """
        Initialize the authentication handler with credential data.

        Args:
            auth_model: The credentials object used to generate the authorization
             header.

        """
        auth_params = {}
        if auth_model is not None \
                and auth_model.x_rapidapi_key is not None:
            auth_params["x-rapidapi-key"] = auth_model.x_rapidapi_key
        super().__init__(auth_params=auth_params)


class ApiKeyCredentials:
    """
    A model for authentication credentials. Provides simple validation,
    cloning support, and optional construction from environment variables.
    Suitable as a pattern for other auth models.
    """

    @property
    def x_rapidapi_key(self):
        """
        Return the stored x_rapidapi_key.
        """
        return self._x_rapidapi_key

    def __init__(self, x_rapidapi_key):
        """
        Initialize the credentials.

        Args:
            x_rapidapi_key: The x_rapidapi_key property value to set.

        Raises:
            ValueError: If any required value is missing.

        """
        if x_rapidapi_key is None:
            raise ValueError("x_rapidapi_key cannot be None")
        self._x_rapidapi_key = x_rapidapi_key

    def clone_with(self, x_rapidapi_key=None):
        """
        Return a new instance with optional value overrides.

        Args:
            x_rapidapi_key: The x_rapidapi_key property value to set.

        """
        return ApiKeyCredentials(x_rapidapi_key or self.x_rapidapi_key)

    @classmethod
    def from_environment(cls):
        """
        Create credentials from environment variables, if available.

        Returns:
            A credentials instance or ``None`` if values are missing.

        """
        x_rapidapi_key = os.getenv(
            "API_KEY_X_RAPIDAPI_KEY",
            None,
        )

        if (x_rapidapi_key is None):
            return None

        return cls(
            x_rapidapi_key=x_rapidapi_key,
        )
