
"""
mediumapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os

from apimatic_core.authentication.header_auth import HeaderAuth


class ApiHost(HeaderAuth):
    """
    An authentication handler that applies `CustomHeaderAuthentication` to
    outgoing requests. It constructs the required credential values and integrates
    with the core authentication framework.
    """

    @property
    def error_message(self):
        """Return reason about the authentication failure."""
        return "ApiHost: x_rapidapi_host is undefined."

    def __init__(self, auth_model):
        """
        Initialize the authentication handler with credential data.

        Args:
            auth_model: The credentials object used to generate the authorization
             header.

        """
        auth_params = {}
        if auth_model is not None \
                and auth_model.x_rapidapi_host is not None:
            auth_params["x-rapidapi-host"] = auth_model.x_rapidapi_host
        super().__init__(auth_params=auth_params)


class ApiHostCredentials:
    """
    A model for authentication credentials. Provides simple validation,
    cloning support, and optional construction from environment variables.
    Suitable as a pattern for other auth models.
    """

    @property
    def x_rapidapi_host(self):
        """
        Return the stored x_rapidapi_host.
        """
        return self._x_rapidapi_host

    def __init__(self, x_rapidapi_host):
        """
        Initialize the credentials.

        Args:
            x_rapidapi_host: The x_rapidapi_host property value to set.

        Raises:
            ValueError: If any required value is missing.

        """
        if x_rapidapi_host is None:
            raise ValueError("x_rapidapi_host cannot be None")
        self._x_rapidapi_host = x_rapidapi_host

    def clone_with(self, x_rapidapi_host=None):
        """
        Return a new instance with optional value overrides.

        Args:
            x_rapidapi_host: The x_rapidapi_host property value to set.

        """
        return ApiHostCredentials(x_rapidapi_host or self.x_rapidapi_host)

    @classmethod
    def from_environment(cls):
        """
        Create credentials from environment variables, if available.

        Returns:
            A credentials instance or ``None`` if values are missing.

        """
        x_rapidapi_host = os.getenv(
            "API_HOST_X_RAPIDAPI_HOST",
            None,
        )

        if (x_rapidapi_host is None):
            return None

        return cls(
            x_rapidapi_host=x_rapidapi_host,
        )
