"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class ArticleRelatedResponse(object):
    """Implementation of the 'Article Related Response' model.

    Attributes:
        id (str): The model property of type str.
        related_articles (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "related_articles": "related_articles",
    }

    _optionals = [
        "id",
        "related_articles",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        related_articles=APIHelper.SKIP):
        """Initialize a ArticleRelatedResponse instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if related_articles is not APIHelper.SKIP:
            self.related_articles = related_articles

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        related_articles =\
            dictionary.get("related_articles")\
            if dictionary.get("related_articles")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(id,
                   related_articles)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _related_articles=(
            self.related_articles
            if hasattr(self, "related_articles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"related_articles={_related_articles!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _related_articles=(
            self.related_articles
            if hasattr(self, "related_articles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"related_articles={_related_articles!s}, "
            f")"
        )
