"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class ArticleFansResponse(object):
    """Implementation of the 'Article Fans Response' model.

    Attributes:
        article_id (str): The model property of type str.
        count (int): The model property of type int.
        voters (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "article_id": "article_id",
        "count": "count",
        "voters": "voters",
    }

    _optionals = [
        "article_id",
        "count",
        "voters",
    ]

    def __init__(
        self,
        article_id=APIHelper.SKIP,
        count=APIHelper.SKIP,
        voters=APIHelper.SKIP):
        """Initialize a ArticleFansResponse instance."""
        # Initialize members of the class
        if article_id is not APIHelper.SKIP:
            self.article_id = article_id
        if count is not APIHelper.SKIP:
            self.count = count
        if voters is not APIHelper.SKIP:
            self.voters = voters

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        article_id =\
            dictionary.get("article_id")\
            if dictionary.get("article_id")\
                else APIHelper.SKIP
        count =\
            dictionary.get("count")\
            if dictionary.get("count")\
                else APIHelper.SKIP
        voters =\
            dictionary.get("voters")\
            if dictionary.get("voters")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(article_id,
                   count,
                   voters)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _article_id=(
            self.article_id
            if hasattr(self, "article_id")
            else None
        )
        _count=(
            self.count
            if hasattr(self, "count")
            else None
        )
        _voters=(
            self.voters
            if hasattr(self, "voters")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"article_id={_article_id!r}, "
            f"count={_count!r}, "
            f"voters={_voters!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _article_id=(
            self.article_id
            if hasattr(self, "article_id")
            else None
        )
        _count=(
            self.count
            if hasattr(self, "count")
            else None
        )
        _voters=(
            self.voters
            if hasattr(self, "voters")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"article_id={_article_id!s}, "
            f"count={_count!s}, "
            f"voters={_voters!s}, "
            f")"
        )
