"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class ArticleResponsesResponse(object):
    """Implementation of the 'Article Responses Response' model.

    Attributes:
        id (str): The model property of type str.
        responses (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "responses": "responses",
    }

    _optionals = [
        "id",
        "responses",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        responses=APIHelper.SKIP):
        """Initialize a ArticleResponsesResponse instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if responses is not APIHelper.SKIP:
            self.responses = responses

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        responses =\
            dictionary.get("responses")\
            if dictionary.get("responses")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(id,
                   responses)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _responses=(
            self.responses
            if hasattr(self, "responses")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"responses={_responses!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _responses=(
            self.responses
            if hasattr(self, "responses")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"responses={_responses!s}, "
            f")"
        )
