"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class ArticleResponse(object):
    """Implementation of the 'Article Response' model.

    Attributes:
        author (str): The model property of type str.
        claps (int): The model property of type int.
        id (str): The model property of type str.
        image_url (str): The model property of type str.
        is_locked (bool): The model property of type bool.
        is_series (bool): The model property of type bool.
        lang (str): The model property of type str.
        last_modified_at (str): The model property of type str.
        publication_id (str): The model property of type str.
        published_at (str): The model property of type str.
        reading_time (float): The model property of type float.
        responses_count (int): The model property of type int.
        subtitle (str): The model property of type str.
        tags (List[str]): The model property of type List[str].
        title (str): The model property of type str.
        topics (List[str]): The model property of type List[str].
        url (str): The model property of type str.
        voters (int): The model property of type int.
        word_count (int): The model property of type int.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "author": "author",
        "claps": "claps",
        "id": "id",
        "image_url": "image_url",
        "is_locked": "is_locked",
        "is_series": "is_series",
        "lang": "lang",
        "last_modified_at": "last_modified_at",
        "publication_id": "publication_id",
        "published_at": "published_at",
        "reading_time": "reading_time",
        "responses_count": "responses_count",
        "subtitle": "subtitle",
        "tags": "tags",
        "title": "title",
        "topics": "topics",
        "url": "url",
        "voters": "voters",
        "word_count": "word_count",
    }

    _optionals = [
        "author",
        "claps",
        "id",
        "image_url",
        "is_locked",
        "is_series",
        "lang",
        "last_modified_at",
        "publication_id",
        "published_at",
        "reading_time",
        "responses_count",
        "subtitle",
        "tags",
        "title",
        "topics",
        "url",
        "voters",
        "word_count",
    ]

    def __init__(
        self,
        author=APIHelper.SKIP,
        claps=APIHelper.SKIP,
        id=APIHelper.SKIP,
        image_url=APIHelper.SKIP,
        is_locked=APIHelper.SKIP,
        is_series=APIHelper.SKIP,
        lang=APIHelper.SKIP,
        last_modified_at=APIHelper.SKIP,
        publication_id=APIHelper.SKIP,
        published_at=APIHelper.SKIP,
        reading_time=APIHelper.SKIP,
        responses_count=APIHelper.SKIP,
        subtitle=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        title=APIHelper.SKIP,
        topics=APIHelper.SKIP,
        url=APIHelper.SKIP,
        voters=APIHelper.SKIP,
        word_count=APIHelper.SKIP):
        """Initialize a ArticleResponse instance."""
        # Initialize members of the class
        if author is not APIHelper.SKIP:
            self.author = author
        if claps is not APIHelper.SKIP:
            self.claps = claps
        if id is not APIHelper.SKIP:
            self.id = id
        if image_url is not APIHelper.SKIP:
            self.image_url = image_url
        if is_locked is not APIHelper.SKIP:
            self.is_locked = is_locked
        if is_series is not APIHelper.SKIP:
            self.is_series = is_series
        if lang is not APIHelper.SKIP:
            self.lang = lang
        if last_modified_at is not APIHelper.SKIP:
            self.last_modified_at = last_modified_at
        if publication_id is not APIHelper.SKIP:
            self.publication_id = publication_id
        if published_at is not APIHelper.SKIP:
            self.published_at = published_at
        if reading_time is not APIHelper.SKIP:
            self.reading_time = reading_time
        if responses_count is not APIHelper.SKIP:
            self.responses_count = responses_count
        if subtitle is not APIHelper.SKIP:
            self.subtitle = subtitle
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if title is not APIHelper.SKIP:
            self.title = title
        if topics is not APIHelper.SKIP:
            self.topics = topics
        if url is not APIHelper.SKIP:
            self.url = url
        if voters is not APIHelper.SKIP:
            self.voters = voters
        if word_count is not APIHelper.SKIP:
            self.word_count = word_count

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        author =\
            dictionary.get("author")\
            if dictionary.get("author")\
                else APIHelper.SKIP
        claps =\
            dictionary.get("claps")\
            if dictionary.get("claps")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        image_url =\
            dictionary.get("image_url")\
            if dictionary.get("image_url")\
                else APIHelper.SKIP
        is_locked =\
            dictionary.get("is_locked")\
            if "is_locked" in dictionary.keys()\
                else APIHelper.SKIP
        is_series =\
            dictionary.get("is_series")\
            if "is_series" in dictionary.keys()\
                else APIHelper.SKIP
        lang =\
            dictionary.get("lang")\
            if dictionary.get("lang")\
                else APIHelper.SKIP
        last_modified_at =\
            dictionary.get("last_modified_at")\
            if dictionary.get("last_modified_at")\
                else APIHelper.SKIP
        publication_id =\
            dictionary.get("publication_id")\
            if dictionary.get("publication_id")\
                else APIHelper.SKIP
        published_at =\
            dictionary.get("published_at")\
            if dictionary.get("published_at")\
                else APIHelper.SKIP
        reading_time =\
            dictionary.get("reading_time")\
            if dictionary.get("reading_time")\
                else APIHelper.SKIP
        responses_count =\
            dictionary.get("responses_count")\
            if dictionary.get("responses_count")\
                else APIHelper.SKIP
        subtitle =\
            dictionary.get("subtitle")\
            if dictionary.get("subtitle")\
                else APIHelper.SKIP
        tags =\
            dictionary.get("tags")\
            if dictionary.get("tags")\
                else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP
        topics =\
            dictionary.get("topics")\
            if dictionary.get("topics")\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP
        voters =\
            dictionary.get("voters")\
            if dictionary.get("voters")\
                else APIHelper.SKIP
        word_count =\
            dictionary.get("word_count")\
            if dictionary.get("word_count")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(author,
                   claps,
                   id,
                   image_url,
                   is_locked,
                   is_series,
                   lang,
                   last_modified_at,
                   publication_id,
                   published_at,
                   reading_time,
                   responses_count,
                   subtitle,
                   tags,
                   title,
                   topics,
                   url,
                   voters,
                   word_count)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _author=(
            self.author
            if hasattr(self, "author")
            else None
        )
        _claps=(
            self.claps
            if hasattr(self, "claps")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _is_locked=(
            self.is_locked
            if hasattr(self, "is_locked")
            else None
        )
        _is_series=(
            self.is_series
            if hasattr(self, "is_series")
            else None
        )
        _lang=(
            self.lang
            if hasattr(self, "lang")
            else None
        )
        _last_modified_at=(
            self.last_modified_at
            if hasattr(self, "last_modified_at")
            else None
        )
        _publication_id=(
            self.publication_id
            if hasattr(self, "publication_id")
            else None
        )
        _published_at=(
            self.published_at
            if hasattr(self, "published_at")
            else None
        )
        _reading_time=(
            self.reading_time
            if hasattr(self, "reading_time")
            else None
        )
        _responses_count=(
            self.responses_count
            if hasattr(self, "responses_count")
            else None
        )
        _subtitle=(
            self.subtitle
            if hasattr(self, "subtitle")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _topics=(
            self.topics
            if hasattr(self, "topics")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _voters=(
            self.voters
            if hasattr(self, "voters")
            else None
        )
        _word_count=(
            self.word_count
            if hasattr(self, "word_count")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"author={_author!r}, "
            f"claps={_claps!r}, "
            f"id={_id!r}, "
            f"image_url={_image_url!r}, "
            f"is_locked={_is_locked!r}, "
            f"is_series={_is_series!r}, "
            f"lang={_lang!r}, "
            f"last_modified_at={_last_modified_at!r}, "
            f"publication_id={_publication_id!r}, "
            f"published_at={_published_at!r}, "
            f"reading_time={_reading_time!r}, "
            f"responses_count={_responses_count!r}, "
            f"subtitle={_subtitle!r}, "
            f"tags={_tags!r}, "
            f"title={_title!r}, "
            f"topics={_topics!r}, "
            f"url={_url!r}, "
            f"voters={_voters!r}, "
            f"word_count={_word_count!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _author=(
            self.author
            if hasattr(self, "author")
            else None
        )
        _claps=(
            self.claps
            if hasattr(self, "claps")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _is_locked=(
            self.is_locked
            if hasattr(self, "is_locked")
            else None
        )
        _is_series=(
            self.is_series
            if hasattr(self, "is_series")
            else None
        )
        _lang=(
            self.lang
            if hasattr(self, "lang")
            else None
        )
        _last_modified_at=(
            self.last_modified_at
            if hasattr(self, "last_modified_at")
            else None
        )
        _publication_id=(
            self.publication_id
            if hasattr(self, "publication_id")
            else None
        )
        _published_at=(
            self.published_at
            if hasattr(self, "published_at")
            else None
        )
        _reading_time=(
            self.reading_time
            if hasattr(self, "reading_time")
            else None
        )
        _responses_count=(
            self.responses_count
            if hasattr(self, "responses_count")
            else None
        )
        _subtitle=(
            self.subtitle
            if hasattr(self, "subtitle")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _topics=(
            self.topics
            if hasattr(self, "topics")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _voters=(
            self.voters
            if hasattr(self, "voters")
            else None
        )
        _word_count=(
            self.word_count
            if hasattr(self, "word_count")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"author={_author!s}, "
            f"claps={_claps!s}, "
            f"id={_id!s}, "
            f"image_url={_image_url!s}, "
            f"is_locked={_is_locked!s}, "
            f"is_series={_is_series!s}, "
            f"lang={_lang!s}, "
            f"last_modified_at={_last_modified_at!s}, "
            f"publication_id={_publication_id!s}, "
            f"published_at={_published_at!s}, "
            f"reading_time={_reading_time!s}, "
            f"responses_count={_responses_count!s}, "
            f"subtitle={_subtitle!s}, "
            f"tags={_tags!s}, "
            f"title={_title!s}, "
            f"topics={_topics!s}, "
            f"url={_url!s}, "
            f"voters={_voters!s}, "
            f"word_count={_word_count!s}, "
            f")"
        )
