"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class ArticleContentResponse(object):
    """Implementation of the 'Article Content Response' model.

    Attributes:
        content (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "content": "content",
    }

    _optionals = [
        "content",
    ]

    def __init__(
        self,
        content=APIHelper.SKIP):
        """Initialize a ArticleContentResponse instance."""
        # Initialize members of the class
        if content is not APIHelper.SKIP:
            self.content = content

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        content =\
            dictionary.get("content")\
            if dictionary.get("content")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(content)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"content={_content!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"content={_content!s}, "
            f")"
        )
