"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class ArticleMarkdownResponse(object):
    """Implementation of the 'Article Markdown Response' model.

    Attributes:
        markdown (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "markdown": "markdown",
    }

    _optionals = [
        "markdown",
    ]

    def __init__(
        self,
        markdown=APIHelper.SKIP):
        """Initialize a ArticleMarkdownResponse instance."""
        # Initialize members of the class
        if markdown is not APIHelper.SKIP:
            self.markdown = markdown

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        markdown =\
            dictionary.get("markdown")\
            if dictionary.get("markdown")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(markdown)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _markdown=(
            self.markdown
            if hasattr(self, "markdown")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"markdown={_markdown!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _markdown=(
            self.markdown
            if hasattr(self, "markdown")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"markdown={_markdown!s}, "
            f")"
        )
