"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class ListArticlesResponse(object):
    """Implementation of the 'List Articles Response' model.

    Attributes:
        id (str): The model property of type str.
        list_articles (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "list_articles": "list_articles",
    }

    _optionals = [
        "id",
        "list_articles",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        list_articles=APIHelper.SKIP):
        """Initialize a ListArticlesResponse instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if list_articles is not APIHelper.SKIP:
            self.list_articles = list_articles

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        list_articles =\
            dictionary.get("list_articles")\
            if dictionary.get("list_articles")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(id,
                   list_articles)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _list_articles=(
            self.list_articles
            if hasattr(self, "list_articles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"list_articles={_list_articles!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _list_articles=(
            self.list_articles
            if hasattr(self, "list_articles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"list_articles={_list_articles!s}, "
            f")"
        )
