"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class ListResponse(object):
    """Implementation of the 'List Response' model.

    Attributes:
        author (str): `user_id` of the author
        claps (int): The model property of type int.
        count (int): Number of articles in the list
        created_at (str): The model property of type str.
        description (str): The model property of type str.
        id (str): The model property of type str.
        last_item_inserted_at (str): The model property of type str.
        name (str): The model property of type str.
        responses_count (int): The model property of type int.
        thumbnail (str): Image URL
        voters (int): The model property of type int.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "author": "author",
        "claps": "claps",
        "count": "count",
        "created_at": "created_at",
        "description": "description",
        "id": "id",
        "last_item_inserted_at": "last_item_inserted_at",
        "name": "name",
        "responses_count": "responses_count",
        "thumbnail": "thumbnail",
        "voters": "voters",
    }

    _optionals = [
        "author",
        "claps",
        "count",
        "created_at",
        "description",
        "id",
        "last_item_inserted_at",
        "name",
        "responses_count",
        "thumbnail",
        "voters",
    ]

    def __init__(
        self,
        author=APIHelper.SKIP,
        claps=APIHelper.SKIP,
        count=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        description=APIHelper.SKIP,
        id=APIHelper.SKIP,
        last_item_inserted_at=APIHelper.SKIP,
        name=APIHelper.SKIP,
        responses_count=APIHelper.SKIP,
        thumbnail=APIHelper.SKIP,
        voters=APIHelper.SKIP):
        """Initialize a ListResponse instance."""
        # Initialize members of the class
        if author is not APIHelper.SKIP:
            self.author = author
        if claps is not APIHelper.SKIP:
            self.claps = claps
        if count is not APIHelper.SKIP:
            self.count = count
        if created_at is not APIHelper.SKIP:
            self.created_at = created_at
        if description is not APIHelper.SKIP:
            self.description = description
        if id is not APIHelper.SKIP:
            self.id = id
        if last_item_inserted_at is not APIHelper.SKIP:
            self.last_item_inserted_at = last_item_inserted_at
        if name is not APIHelper.SKIP:
            self.name = name
        if responses_count is not APIHelper.SKIP:
            self.responses_count = responses_count
        if thumbnail is not APIHelper.SKIP:
            self.thumbnail = thumbnail
        if voters is not APIHelper.SKIP:
            self.voters = voters

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        author =\
            dictionary.get("author")\
            if dictionary.get("author")\
                else APIHelper.SKIP
        claps =\
            dictionary.get("claps")\
            if dictionary.get("claps")\
                else APIHelper.SKIP
        count =\
            dictionary.get("count")\
            if dictionary.get("count")\
                else APIHelper.SKIP
        created_at =\
            dictionary.get("created_at")\
            if dictionary.get("created_at")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        last_item_inserted_at =\
            dictionary.get("last_item_inserted_at")\
            if dictionary.get("last_item_inserted_at")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        responses_count =\
            dictionary.get("responses_count")\
            if dictionary.get("responses_count")\
                else APIHelper.SKIP
        thumbnail =\
            dictionary.get("thumbnail")\
            if dictionary.get("thumbnail")\
                else APIHelper.SKIP
        voters =\
            dictionary.get("voters")\
            if dictionary.get("voters")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(author,
                   claps,
                   count,
                   created_at,
                   description,
                   id,
                   last_item_inserted_at,
                   name,
                   responses_count,
                   thumbnail,
                   voters)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _author=(
            self.author
            if hasattr(self, "author")
            else None
        )
        _claps=(
            self.claps
            if hasattr(self, "claps")
            else None
        )
        _count=(
            self.count
            if hasattr(self, "count")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _last_item_inserted_at=(
            self.last_item_inserted_at
            if hasattr(self, "last_item_inserted_at")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _responses_count=(
            self.responses_count
            if hasattr(self, "responses_count")
            else None
        )
        _thumbnail=(
            self.thumbnail
            if hasattr(self, "thumbnail")
            else None
        )
        _voters=(
            self.voters
            if hasattr(self, "voters")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"author={_author!r}, "
            f"claps={_claps!r}, "
            f"count={_count!r}, "
            f"created_at={_created_at!r}, "
            f"description={_description!r}, "
            f"id={_id!r}, "
            f"last_item_inserted_at={_last_item_inserted_at!r}, "
            f"name={_name!r}, "
            f"responses_count={_responses_count!r}, "
            f"thumbnail={_thumbnail!r}, "
            f"voters={_voters!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _author=(
            self.author
            if hasattr(self, "author")
            else None
        )
        _claps=(
            self.claps
            if hasattr(self, "claps")
            else None
        )
        _count=(
            self.count
            if hasattr(self, "count")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _last_item_inserted_at=(
            self.last_item_inserted_at
            if hasattr(self, "last_item_inserted_at")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _responses_count=(
            self.responses_count
            if hasattr(self, "responses_count")
            else None
        )
        _thumbnail=(
            self.thumbnail
            if hasattr(self, "thumbnail")
            else None
        )
        _voters=(
            self.voters
            if hasattr(self, "voters")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"author={_author!s}, "
            f"claps={_claps!s}, "
            f"count={_count!s}, "
            f"created_at={_created_at!s}, "
            f"description={_description!s}, "
            f"id={_id!s}, "
            f"last_item_inserted_at={_last_item_inserted_at!s}, "
            f"name={_name!s}, "
            f"responses_count={_responses_count!s}, "
            f"thumbnail={_thumbnail!s}, "
            f"voters={_voters!s}, "
            f")"
        )
