"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class PublicationIdForResponse(object):
    """Implementation of the 'Publication Id For Response' model.

    Attributes:
        publication_id (str): Unique hash id of the publication.
        publication_slug (str): Same publication slug that you passed in the path
            parameters.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "publication_id": "publication_id",
        "publication_slug": "publication_slug",
    }

    _optionals = [
        "publication_id",
        "publication_slug",
    ]

    def __init__(
        self,
        publication_id=APIHelper.SKIP,
        publication_slug=APIHelper.SKIP):
        """Initialize a PublicationIdForResponse instance."""
        # Initialize members of the class
        if publication_id is not APIHelper.SKIP:
            self.publication_id = publication_id
        if publication_slug is not APIHelper.SKIP:
            self.publication_slug = publication_slug

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        publication_id =\
            dictionary.get("publication_id")\
            if dictionary.get("publication_id")\
                else APIHelper.SKIP
        publication_slug =\
            dictionary.get("publication_slug")\
            if dictionary.get("publication_slug")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(publication_id,
                   publication_slug)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _publication_id=(
            self.publication_id
            if hasattr(self, "publication_id")
            else None
        )
        _publication_slug=(
            self.publication_slug
            if hasattr(self, "publication_slug")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"publication_id={_publication_id!r}, "
            f"publication_slug={_publication_slug!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _publication_id=(
            self.publication_id
            if hasattr(self, "publication_id")
            else None
        )
        _publication_slug=(
            self.publication_slug
            if hasattr(self, "publication_slug")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"publication_id={_publication_id!s}, "
            f"publication_slug={_publication_slug!s}, "
            f")"
        )
