"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class PublicationArticlesResponse(object):
    """Implementation of the 'Publication Articles Response' model.

    Attributes:
        publication_articles (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "publication_articles": "publication_articles",
    }

    _optionals = [
        "publication_articles",
    ]

    def __init__(
        self,
        publication_articles=APIHelper.SKIP):
        """Initialize a PublicationArticlesResponse instance."""
        # Initialize members of the class
        if publication_articles is not APIHelper.SKIP:
            self.publication_articles = publication_articles

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        publication_articles =\
            dictionary.get("publication_articles")\
            if dictionary.get("publication_articles")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(publication_articles)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _publication_articles=(
            self.publication_articles
            if hasattr(self, "publication_articles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"publication_articles={_publication_articles!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _publication_articles=(
            self.publication_articles
            if hasattr(self, "publication_articles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"publication_articles={_publication_articles!s}, "
            f")"
        )
