"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class PublicationNewsletterResponse(object):
    """Implementation of the 'Publication Newsletter Response' model.

    Attributes:
        creator_id (str): The model property of type str.
        description (str): The model property of type str.
        id (str): The model property of type str.
        image (str): The model property of type str.
        name (str): The model property of type str.
        slug (str): The model property of type str.
        subscribers (int): The model property of type int.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "creator_id": "creator_id",
        "description": "description",
        "id": "id",
        "image": "image",
        "name": "name",
        "slug": "slug",
        "subscribers": "subscribers",
    }

    _optionals = [
        "creator_id",
        "description",
        "id",
        "image",
        "name",
        "slug",
        "subscribers",
    ]

    def __init__(
        self,
        creator_id=APIHelper.SKIP,
        description=APIHelper.SKIP,
        id=APIHelper.SKIP,
        image=APIHelper.SKIP,
        name=APIHelper.SKIP,
        slug=APIHelper.SKIP,
        subscribers=APIHelper.SKIP):
        """Initialize a PublicationNewsletterResponse instance."""
        # Initialize members of the class
        if creator_id is not APIHelper.SKIP:
            self.creator_id = creator_id
        if description is not APIHelper.SKIP:
            self.description = description
        if id is not APIHelper.SKIP:
            self.id = id
        if image is not APIHelper.SKIP:
            self.image = image
        if name is not APIHelper.SKIP:
            self.name = name
        if slug is not APIHelper.SKIP:
            self.slug = slug
        if subscribers is not APIHelper.SKIP:
            self.subscribers = subscribers

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        creator_id =\
            dictionary.get("creator_id")\
            if dictionary.get("creator_id")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        image =\
            dictionary.get("image")\
            if dictionary.get("image")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        slug =\
            dictionary.get("slug")\
            if dictionary.get("slug")\
                else APIHelper.SKIP
        subscribers =\
            dictionary.get("subscribers")\
            if dictionary.get("subscribers")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(creator_id,
                   description,
                   id,
                   image,
                   name,
                   slug,
                   subscribers)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _creator_id=(
            self.creator_id
            if hasattr(self, "creator_id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _image=(
            self.image
            if hasattr(self, "image")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _slug=(
            self.slug
            if hasattr(self, "slug")
            else None
        )
        _subscribers=(
            self.subscribers
            if hasattr(self, "subscribers")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"creator_id={_creator_id!r}, "
            f"description={_description!r}, "
            f"id={_id!r}, "
            f"image={_image!r}, "
            f"name={_name!r}, "
            f"slug={_slug!r}, "
            f"subscribers={_subscribers!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _creator_id=(
            self.creator_id
            if hasattr(self, "creator_id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _image=(
            self.image
            if hasattr(self, "image")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _slug=(
            self.slug
            if hasattr(self, "slug")
            else None
        )
        _subscribers=(
            self.subscribers
            if hasattr(self, "subscribers")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"creator_id={_creator_id!s}, "
            f"description={_description!s}, "
            f"id={_id!s}, "
            f"image={_image!s}, "
            f"name={_name!s}, "
            f"slug={_slug!s}, "
            f"subscribers={_subscribers!s}, "
            f")"
        )
