"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class PublicationResponse(object):
    """Implementation of the 'Publication Response' model.

    Attributes:
        creator (str): The model property of type str.
        description (str): The model property of type str.
        editors (List[str]): The model property of type List[str].
        facebook_pagename (str): The model property of type str.
        followers (int): The model property of type int.
        id (str): The model property of type str.
        instagram_username (str): The model property of type str.
        name (str): The model property of type str.
        slug (str): The model property of type str.
        tagline (str): The model property of type str.
        tags (List[str]): The model property of type List[str].
        twitter_username (str): The model property of type str.
        url (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "creator": "creator",
        "description": "description",
        "editors": "editors",
        "facebook_pagename": "facebook_pagename",
        "followers": "followers",
        "id": "id",
        "instagram_username": "instagram_username",
        "name": "name",
        "slug": "slug",
        "tagline": "tagline",
        "tags": "tags",
        "twitter_username": "twitter_username",
        "url": "url",
    }

    _optionals = [
        "creator",
        "description",
        "editors",
        "facebook_pagename",
        "followers",
        "id",
        "instagram_username",
        "name",
        "slug",
        "tagline",
        "tags",
        "twitter_username",
        "url",
    ]

    def __init__(
        self,
        creator=APIHelper.SKIP,
        description=APIHelper.SKIP,
        editors=APIHelper.SKIP,
        facebook_pagename=APIHelper.SKIP,
        followers=APIHelper.SKIP,
        id=APIHelper.SKIP,
        instagram_username=APIHelper.SKIP,
        name=APIHelper.SKIP,
        slug=APIHelper.SKIP,
        tagline=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        twitter_username=APIHelper.SKIP,
        url=APIHelper.SKIP):
        """Initialize a PublicationResponse instance."""
        # Initialize members of the class
        if creator is not APIHelper.SKIP:
            self.creator = creator
        if description is not APIHelper.SKIP:
            self.description = description
        if editors is not APIHelper.SKIP:
            self.editors = editors
        if facebook_pagename is not APIHelper.SKIP:
            self.facebook_pagename = facebook_pagename
        if followers is not APIHelper.SKIP:
            self.followers = followers
        if id is not APIHelper.SKIP:
            self.id = id
        if instagram_username is not APIHelper.SKIP:
            self.instagram_username = instagram_username
        if name is not APIHelper.SKIP:
            self.name = name
        if slug is not APIHelper.SKIP:
            self.slug = slug
        if tagline is not APIHelper.SKIP:
            self.tagline = tagline
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if twitter_username is not APIHelper.SKIP:
            self.twitter_username = twitter_username
        if url is not APIHelper.SKIP:
            self.url = url

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        creator =\
            dictionary.get("creator")\
            if dictionary.get("creator")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        editors =\
            dictionary.get("editors")\
            if dictionary.get("editors")\
                else APIHelper.SKIP
        facebook_pagename =\
            dictionary.get("facebook_pagename")\
            if dictionary.get("facebook_pagename")\
                else APIHelper.SKIP
        followers =\
            dictionary.get("followers")\
            if dictionary.get("followers")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        instagram_username =\
            dictionary.get("instagram_username")\
            if dictionary.get("instagram_username")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        slug =\
            dictionary.get("slug")\
            if dictionary.get("slug")\
                else APIHelper.SKIP
        tagline =\
            dictionary.get("tagline")\
            if dictionary.get("tagline")\
                else APIHelper.SKIP
        tags =\
            dictionary.get("tags")\
            if dictionary.get("tags")\
                else APIHelper.SKIP
        twitter_username =\
            dictionary.get("twitter_username")\
            if dictionary.get("twitter_username")\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(creator,
                   description,
                   editors,
                   facebook_pagename,
                   followers,
                   id,
                   instagram_username,
                   name,
                   slug,
                   tagline,
                   tags,
                   twitter_username,
                   url)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _creator=(
            self.creator
            if hasattr(self, "creator")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _editors=(
            self.editors
            if hasattr(self, "editors")
            else None
        )
        _facebook_pagename=(
            self.facebook_pagename
            if hasattr(self, "facebook_pagename")
            else None
        )
        _followers=(
            self.followers
            if hasattr(self, "followers")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _instagram_username=(
            self.instagram_username
            if hasattr(self, "instagram_username")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _slug=(
            self.slug
            if hasattr(self, "slug")
            else None
        )
        _tagline=(
            self.tagline
            if hasattr(self, "tagline")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _twitter_username=(
            self.twitter_username
            if hasattr(self, "twitter_username")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"creator={_creator!r}, "
            f"description={_description!r}, "
            f"editors={_editors!r}, "
            f"facebook_pagename={_facebook_pagename!r}, "
            f"followers={_followers!r}, "
            f"id={_id!r}, "
            f"instagram_username={_instagram_username!r}, "
            f"name={_name!r}, "
            f"slug={_slug!r}, "
            f"tagline={_tagline!r}, "
            f"tags={_tags!r}, "
            f"twitter_username={_twitter_username!r}, "
            f"url={_url!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _creator=(
            self.creator
            if hasattr(self, "creator")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _editors=(
            self.editors
            if hasattr(self, "editors")
            else None
        )
        _facebook_pagename=(
            self.facebook_pagename
            if hasattr(self, "facebook_pagename")
            else None
        )
        _followers=(
            self.followers
            if hasattr(self, "followers")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _instagram_username=(
            self.instagram_username
            if hasattr(self, "instagram_username")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _slug=(
            self.slug
            if hasattr(self, "slug")
            else None
        )
        _tagline=(
            self.tagline
            if hasattr(self, "tagline")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _twitter_username=(
            self.twitter_username
            if hasattr(self, "twitter_username")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"creator={_creator!s}, "
            f"description={_description!s}, "
            f"editors={_editors!s}, "
            f"facebook_pagename={_facebook_pagename!s}, "
            f"followers={_followers!s}, "
            f"id={_id!s}, "
            f"instagram_username={_instagram_username!s}, "
            f"name={_name!s}, "
            f"slug={_slug!s}, "
            f"tagline={_tagline!s}, "
            f"tags={_tags!s}, "
            f"twitter_username={_twitter_username!s}, "
            f"url={_url!s}, "
            f")"
        )
