"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class RelatedTagsResponse(object):
    """Implementation of the 'Related Tags Response' model.

    Attributes:
        given_tag (str): The model property of type str.
        related_tags (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "given_tag": "given_tag",
        "related_tags": "related_tags",
    }

    _optionals = [
        "given_tag",
        "related_tags",
    ]

    def __init__(
        self,
        given_tag=APIHelper.SKIP,
        related_tags=APIHelper.SKIP):
        """Initialize a RelatedTagsResponse instance."""
        # Initialize members of the class
        if given_tag is not APIHelper.SKIP:
            self.given_tag = given_tag
        if related_tags is not APIHelper.SKIP:
            self.related_tags = related_tags

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        given_tag =\
            dictionary.get("given_tag")\
            if dictionary.get("given_tag")\
                else APIHelper.SKIP
        related_tags =\
            dictionary.get("related_tags")\
            if dictionary.get("related_tags")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(given_tag,
                   related_tags)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _given_tag=(
            self.given_tag
            if hasattr(self, "given_tag")
            else None
        )
        _related_tags=(
            self.related_tags
            if hasattr(self, "related_tags")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"given_tag={_given_tag!r}, "
            f"related_tags={_related_tags!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _given_tag=(
            self.given_tag
            if hasattr(self, "given_tag")
            else None
        )
        _related_tags=(
            self.related_tags
            if hasattr(self, "related_tags")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"given_tag={_given_tag!s}, "
            f"related_tags={_related_tags!s}, "
            f")"
        )
