"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class Response(object):
    """Implementation of the 'Response' model.

    Attributes:
        developer (str): Full name of the API's developer
        documentation (str): Link to the Medium API's documentation
        email (str): Email ID of the developer
        linkedin (str): LinkedIn Page URL
        name (str): Full name of the API
        twitter (str): Twitter Profile URL
        website (str): Link to the Medium API's website

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "developer": "developer",
        "documentation": "documentation",
        "email": "email",
        "linkedin": "linkedin",
        "name": "name",
        "twitter": "twitter",
        "website": "website",
    }

    _optionals = [
        "developer",
        "documentation",
        "email",
        "linkedin",
        "name",
        "twitter",
        "website",
    ]

    def __init__(
        self,
        developer=APIHelper.SKIP,
        documentation=APIHelper.SKIP,
        email=APIHelper.SKIP,
        linkedin=APIHelper.SKIP,
        name=APIHelper.SKIP,
        twitter=APIHelper.SKIP,
        website=APIHelper.SKIP):
        """Initialize a Response instance."""
        # Initialize members of the class
        if developer is not APIHelper.SKIP:
            self.developer = developer
        if documentation is not APIHelper.SKIP:
            self.documentation = documentation
        if email is not APIHelper.SKIP:
            self.email = email
        if linkedin is not APIHelper.SKIP:
            self.linkedin = linkedin
        if name is not APIHelper.SKIP:
            self.name = name
        if twitter is not APIHelper.SKIP:
            self.twitter = twitter
        if website is not APIHelper.SKIP:
            self.website = website

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        developer =\
            dictionary.get("developer")\
            if dictionary.get("developer")\
                else APIHelper.SKIP
        documentation =\
            dictionary.get("documentation")\
            if dictionary.get("documentation")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        linkedin =\
            dictionary.get("linkedin")\
            if dictionary.get("linkedin")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        twitter =\
            dictionary.get("twitter")\
            if dictionary.get("twitter")\
                else APIHelper.SKIP
        website =\
            dictionary.get("website")\
            if dictionary.get("website")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(developer,
                   documentation,
                   email,
                   linkedin,
                   name,
                   twitter,
                   website)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _developer=(
            self.developer
            if hasattr(self, "developer")
            else None
        )
        _documentation=(
            self.documentation
            if hasattr(self, "documentation")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _linkedin=(
            self.linkedin
            if hasattr(self, "linkedin")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _twitter=(
            self.twitter
            if hasattr(self, "twitter")
            else None
        )
        _website=(
            self.website
            if hasattr(self, "website")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"developer={_developer!r}, "
            f"documentation={_documentation!r}, "
            f"email={_email!r}, "
            f"linkedin={_linkedin!r}, "
            f"name={_name!r}, "
            f"twitter={_twitter!r}, "
            f"website={_website!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _developer=(
            self.developer
            if hasattr(self, "developer")
            else None
        )
        _documentation=(
            self.documentation
            if hasattr(self, "documentation")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _linkedin=(
            self.linkedin
            if hasattr(self, "linkedin")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _twitter=(
            self.twitter
            if hasattr(self, "twitter")
            else None
        )
        _website=(
            self.website
            if hasattr(self, "website")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"developer={_developer!s}, "
            f"documentation={_documentation!s}, "
            f"email={_email!s}, "
            f"linkedin={_linkedin!s}, "
            f"name={_name!s}, "
            f"twitter={_twitter!s}, "
            f"website={_website!s}, "
            f")"
        )
