"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class SearchUsersResponse(object):
    """Implementation of the 'Search Users Response' model.

    Attributes:
        search_query (str): The model property of type str.
        users (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "search_query": "search_query",
        "users": "users",
    }

    _optionals = [
        "search_query",
        "users",
    ]

    def __init__(
        self,
        search_query=APIHelper.SKIP,
        users=APIHelper.SKIP):
        """Initialize a SearchUsersResponse instance."""
        # Initialize members of the class
        if search_query is not APIHelper.SKIP:
            self.search_query = search_query
        if users is not APIHelper.SKIP:
            self.users = users

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        search_query =\
            dictionary.get("search_query")\
            if dictionary.get("search_query")\
                else APIHelper.SKIP
        users =\
            dictionary.get("users")\
            if dictionary.get("users")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(search_query,
                   users)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _search_query=(
            self.search_query
            if hasattr(self, "search_query")
            else None
        )
        _users=(
            self.users
            if hasattr(self, "users")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"search_query={_search_query!r}, "
            f"users={_users!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _search_query=(
            self.search_query
            if hasattr(self, "search_query")
            else None
        )
        _users=(
            self.users
            if hasattr(self, "users")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"search_query={_search_query!s}, "
            f"users={_users!s}, "
            f")"
        )
