"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class SearchTagsResponse(object):
    """Implementation of the 'Search Tags Response' model.

    Attributes:
        search_query (str): The model property of type str.
        tags (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "search_query": "search_query",
        "tags": "tags",
    }

    _optionals = [
        "search_query",
        "tags",
    ]

    def __init__(
        self,
        search_query=APIHelper.SKIP,
        tags=APIHelper.SKIP):
        """Initialize a SearchTagsResponse instance."""
        # Initialize members of the class
        if search_query is not APIHelper.SKIP:
            self.search_query = search_query
        if tags is not APIHelper.SKIP:
            self.tags = tags

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        search_query =\
            dictionary.get("search_query")\
            if dictionary.get("search_query")\
                else APIHelper.SKIP
        tags =\
            dictionary.get("tags")\
            if dictionary.get("tags")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(search_query,
                   tags)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _search_query=(
            self.search_query
            if hasattr(self, "search_query")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"search_query={_search_query!r}, "
            f"tags={_tags!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _search_query=(
            self.search_query
            if hasattr(self, "search_query")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"search_query={_search_query!s}, "
            f"tags={_tags!s}, "
            f")"
        )
