"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class SearchPublicationsResponse(object):
    """Implementation of the 'Search Publications Response' model.

    Attributes:
        publications (List[str]): The model property of type List[str].
        search_query (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "publications": "publications",
        "search_query": "search_query",
    }

    _optionals = [
        "publications",
        "search_query",
    ]

    def __init__(
        self,
        publications=APIHelper.SKIP,
        search_query=APIHelper.SKIP):
        """Initialize a SearchPublicationsResponse instance."""
        # Initialize members of the class
        if publications is not APIHelper.SKIP:
            self.publications = publications
        if search_query is not APIHelper.SKIP:
            self.search_query = search_query

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        publications =\
            dictionary.get("publications")\
            if dictionary.get("publications")\
                else APIHelper.SKIP
        search_query =\
            dictionary.get("search_query")\
            if dictionary.get("search_query")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(publications,
                   search_query)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _publications=(
            self.publications
            if hasattr(self, "publications")
            else None
        )
        _search_query=(
            self.search_query
            if hasattr(self, "search_query")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"publications={_publications!r}, "
            f"search_query={_search_query!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _publications=(
            self.publications
            if hasattr(self, "publications")
            else None
        )
        _search_query=(
            self.search_query
            if hasattr(self, "search_query")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"publications={_publications!s}, "
            f"search_query={_search_query!s}, "
            f")"
        )
