"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class TopWriterResponse(object):
    """Implementation of the 'Top Writer Response' model.

    Attributes:
        top_writers (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "top_writers": "top_writers",
    }

    _optionals = [
        "top_writers",
    ]

    def __init__(
        self,
        top_writers=APIHelper.SKIP):
        """Initialize a TopWriterResponse instance."""
        # Initialize members of the class
        if top_writers is not APIHelper.SKIP:
            self.top_writers = top_writers

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        top_writers =\
            dictionary.get("top_writers")\
            if dictionary.get("top_writers")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(top_writers)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _top_writers=(
            self.top_writers
            if hasattr(self, "top_writers")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"top_writers={_top_writers!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _top_writers=(
            self.top_writers
            if hasattr(self, "top_writers")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"top_writers={_top_writers!s}, "
            f")"
        )
