"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class TopfeedsResponse(object):
    """Implementation of the 'Topfeeds Response' model.

    Attributes:
        topfeeds (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "topfeeds": "topfeeds",
    }

    _optionals = [
        "topfeeds",
    ]

    def __init__(
        self,
        topfeeds=APIHelper.SKIP):
        """Initialize a TopfeedsResponse instance."""
        # Initialize members of the class
        if topfeeds is not APIHelper.SKIP:
            self.topfeeds = topfeeds

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        topfeeds =\
            dictionary.get("topfeeds")\
            if dictionary.get("topfeeds")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(topfeeds)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _topfeeds=(
            self.topfeeds
            if hasattr(self, "topfeeds")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"topfeeds={_topfeeds!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _topfeeds=(
            self.topfeeds
            if hasattr(self, "topfeeds")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"topfeeds={_topfeeds!s}, "
            f")"
        )
