"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class UserResponse(object):
    """Implementation of the 'User Response' model.

    Attributes:
        allow_notes (bool): The model property of type bool.
        bio (str): The model property of type str.
        followers_count (int): The model property of type int.
        following_count (int): The model property of type int.
        fullname (str): The model property of type str.
        has_list (bool): The model property of type bool.
        id (str): The model property of type str.
        image_url (str): The model property of type str.
        is_book_author (bool): The model property of type bool.
        is_suspended (bool): The model property of type bool.
        is_writer_program_enrolled (bool): The model property of type bool.
        medium_member_at (str): The model property of type str.
        top_writer_in (List[str]): The model property of type List[str].
        twitter_username (str): The model property of type str.
        username (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "allow_notes": "allow_notes",
        "bio": "bio",
        "followers_count": "followers_count",
        "following_count": "following_count",
        "fullname": "fullname",
        "has_list": "has_list",
        "id": "id",
        "image_url": "image_url",
        "is_book_author": "is_book_author",
        "is_suspended": "is_suspended",
        "is_writer_program_enrolled": "is_writer_program_enrolled",
        "medium_member_at": "medium_member_at",
        "top_writer_in": "top_writer_in",
        "twitter_username": "twitter_username",
        "username": "username",
    }

    _optionals = [
        "allow_notes",
        "bio",
        "followers_count",
        "following_count",
        "fullname",
        "has_list",
        "id",
        "image_url",
        "is_book_author",
        "is_suspended",
        "is_writer_program_enrolled",
        "medium_member_at",
        "top_writer_in",
        "twitter_username",
        "username",
    ]

    def __init__(
        self,
        allow_notes=APIHelper.SKIP,
        bio=APIHelper.SKIP,
        followers_count=APIHelper.SKIP,
        following_count=APIHelper.SKIP,
        fullname=APIHelper.SKIP,
        has_list=APIHelper.SKIP,
        id=APIHelper.SKIP,
        image_url=APIHelper.SKIP,
        is_book_author=APIHelper.SKIP,
        is_suspended=APIHelper.SKIP,
        is_writer_program_enrolled=APIHelper.SKIP,
        medium_member_at=APIHelper.SKIP,
        top_writer_in=APIHelper.SKIP,
        twitter_username=APIHelper.SKIP,
        username=APIHelper.SKIP):
        """Initialize a UserResponse instance."""
        # Initialize members of the class
        if allow_notes is not APIHelper.SKIP:
            self.allow_notes = allow_notes
        if bio is not APIHelper.SKIP:
            self.bio = bio
        if followers_count is not APIHelper.SKIP:
            self.followers_count = followers_count
        if following_count is not APIHelper.SKIP:
            self.following_count = following_count
        if fullname is not APIHelper.SKIP:
            self.fullname = fullname
        if has_list is not APIHelper.SKIP:
            self.has_list = has_list
        if id is not APIHelper.SKIP:
            self.id = id
        if image_url is not APIHelper.SKIP:
            self.image_url = image_url
        if is_book_author is not APIHelper.SKIP:
            self.is_book_author = is_book_author
        if is_suspended is not APIHelper.SKIP:
            self.is_suspended = is_suspended
        if is_writer_program_enrolled is not APIHelper.SKIP:
            self.is_writer_program_enrolled = is_writer_program_enrolled
        if medium_member_at is not APIHelper.SKIP:
            self.medium_member_at = medium_member_at
        if top_writer_in is not APIHelper.SKIP:
            self.top_writer_in = top_writer_in
        if twitter_username is not APIHelper.SKIP:
            self.twitter_username = twitter_username
        if username is not APIHelper.SKIP:
            self.username = username

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        allow_notes =\
            dictionary.get("allow_notes")\
            if "allow_notes" in dictionary.keys()\
                else APIHelper.SKIP
        bio =\
            dictionary.get("bio")\
            if dictionary.get("bio")\
                else APIHelper.SKIP
        followers_count =\
            dictionary.get("followers_count")\
            if dictionary.get("followers_count")\
                else APIHelper.SKIP
        following_count =\
            dictionary.get("following_count")\
            if dictionary.get("following_count")\
                else APIHelper.SKIP
        fullname =\
            dictionary.get("fullname")\
            if dictionary.get("fullname")\
                else APIHelper.SKIP
        has_list =\
            dictionary.get("has_list")\
            if "has_list" in dictionary.keys()\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        image_url =\
            dictionary.get("image_url")\
            if dictionary.get("image_url")\
                else APIHelper.SKIP
        is_book_author =\
            dictionary.get("is_book_author")\
            if "is_book_author" in dictionary.keys()\
                else APIHelper.SKIP
        is_suspended =\
            dictionary.get("is_suspended")\
            if "is_suspended" in dictionary.keys()\
                else APIHelper.SKIP
        is_writer_program_enrolled =\
            dictionary.get("is_writer_program_enrolled")\
            if "is_writer_program_enrolled" in dictionary.keys()\
                else APIHelper.SKIP
        medium_member_at =\
            dictionary.get("medium_member_at")\
            if dictionary.get("medium_member_at")\
                else APIHelper.SKIP
        top_writer_in =\
            dictionary.get("top_writer_in")\
            if dictionary.get("top_writer_in")\
                else APIHelper.SKIP
        twitter_username =\
            dictionary.get("twitter_username")\
            if dictionary.get("twitter_username")\
                else APIHelper.SKIP
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(allow_notes,
                   bio,
                   followers_count,
                   following_count,
                   fullname,
                   has_list,
                   id,
                   image_url,
                   is_book_author,
                   is_suspended,
                   is_writer_program_enrolled,
                   medium_member_at,
                   top_writer_in,
                   twitter_username,
                   username)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _allow_notes=(
            self.allow_notes
            if hasattr(self, "allow_notes")
            else None
        )
        _bio=(
            self.bio
            if hasattr(self, "bio")
            else None
        )
        _followers_count=(
            self.followers_count
            if hasattr(self, "followers_count")
            else None
        )
        _following_count=(
            self.following_count
            if hasattr(self, "following_count")
            else None
        )
        _fullname=(
            self.fullname
            if hasattr(self, "fullname")
            else None
        )
        _has_list=(
            self.has_list
            if hasattr(self, "has_list")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _is_book_author=(
            self.is_book_author
            if hasattr(self, "is_book_author")
            else None
        )
        _is_suspended=(
            self.is_suspended
            if hasattr(self, "is_suspended")
            else None
        )
        _is_writer_program_enrolled=(
            self.is_writer_program_enrolled
            if hasattr(self, "is_writer_program_enrolled")
            else None
        )
        _medium_member_at=(
            self.medium_member_at
            if hasattr(self, "medium_member_at")
            else None
        )
        _top_writer_in=(
            self.top_writer_in
            if hasattr(self, "top_writer_in")
            else None
        )
        _twitter_username=(
            self.twitter_username
            if hasattr(self, "twitter_username")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"allow_notes={_allow_notes!r}, "
            f"bio={_bio!r}, "
            f"followers_count={_followers_count!r}, "
            f"following_count={_following_count!r}, "
            f"fullname={_fullname!r}, "
            f"has_list={_has_list!r}, "
            f"id={_id!r}, "
            f"image_url={_image_url!r}, "
            f"is_book_author={_is_book_author!r}, "
            f"is_suspended={_is_suspended!r}, "
            f"is_writer_program_enrolled={_is_writer_program_enrolled!r}, "
            f"medium_member_at={_medium_member_at!r}, "
            f"top_writer_in={_top_writer_in!r}, "
            f"twitter_username={_twitter_username!r}, "
            f"username={_username!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _allow_notes=(
            self.allow_notes
            if hasattr(self, "allow_notes")
            else None
        )
        _bio=(
            self.bio
            if hasattr(self, "bio")
            else None
        )
        _followers_count=(
            self.followers_count
            if hasattr(self, "followers_count")
            else None
        )
        _following_count=(
            self.following_count
            if hasattr(self, "following_count")
            else None
        )
        _fullname=(
            self.fullname
            if hasattr(self, "fullname")
            else None
        )
        _has_list=(
            self.has_list
            if hasattr(self, "has_list")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _is_book_author=(
            self.is_book_author
            if hasattr(self, "is_book_author")
            else None
        )
        _is_suspended=(
            self.is_suspended
            if hasattr(self, "is_suspended")
            else None
        )
        _is_writer_program_enrolled=(
            self.is_writer_program_enrolled
            if hasattr(self, "is_writer_program_enrolled")
            else None
        )
        _medium_member_at=(
            self.medium_member_at
            if hasattr(self, "medium_member_at")
            else None
        )
        _top_writer_in=(
            self.top_writer_in
            if hasattr(self, "top_writer_in")
            else None
        )
        _twitter_username=(
            self.twitter_username
            if hasattr(self, "twitter_username")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"allow_notes={_allow_notes!s}, "
            f"bio={_bio!s}, "
            f"followers_count={_followers_count!s}, "
            f"following_count={_following_count!s}, "
            f"fullname={_fullname!s}, "
            f"has_list={_has_list!s}, "
            f"id={_id!s}, "
            f"image_url={_image_url!s}, "
            f"is_book_author={_is_book_author!s}, "
            f"is_suspended={_is_suspended!s}, "
            f"is_writer_program_enrolled={_is_writer_program_enrolled!s}, "
            f"medium_member_at={_medium_member_at!s}, "
            f"top_writer_in={_top_writer_in!s}, "
            f"twitter_username={_twitter_username!s}, "
            f"username={_username!s}, "
            f")"
        )
