"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class UserFollowersResponse(object):
    """Implementation of the 'User Followers Response' model.

    Attributes:
        followers (List[str]): The model property of type List[str].
        id (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "followers": "followers",
        "id": "id",
    }

    _optionals = [
        "followers",
        "id",
    ]

    def __init__(
        self,
        followers=APIHelper.SKIP,
        id=APIHelper.SKIP):
        """Initialize a UserFollowersResponse instance."""
        # Initialize members of the class
        if followers is not APIHelper.SKIP:
            self.followers = followers
        if id is not APIHelper.SKIP:
            self.id = id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        followers =\
            dictionary.get("followers")\
            if dictionary.get("followers")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(followers,
                   id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _followers=(
            self.followers
            if hasattr(self, "followers")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"followers={_followers!r}, "
            f"id={_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _followers=(
            self.followers
            if hasattr(self, "followers")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"followers={_followers!s}, "
            f"id={_id!s}, "
            f")"
        )
