"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class UserInterestsResponse(object):
    """Implementation of the 'User Interests Response' model.

    Attributes:
        tags_followed (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tags_followed": "tags_followed",
    }

    _optionals = [
        "tags_followed",
    ]

    def __init__(
        self,
        tags_followed=APIHelper.SKIP):
        """Initialize a UserInterestsResponse instance."""
        # Initialize members of the class
        if tags_followed is not APIHelper.SKIP:
            self.tags_followed = tags_followed

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        tags_followed =\
            dictionary.get("tags_followed")\
            if dictionary.get("tags_followed")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(tags_followed)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _tags_followed=(
            self.tags_followed
            if hasattr(self, "tags_followed")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"tags_followed={_tags_followed!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _tags_followed=(
            self.tags_followed
            if hasattr(self, "tags_followed")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"tags_followed={_tags_followed!s}, "
            f")"
        )
