"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class UserPublicationsResponse(object):
    """Implementation of the 'User Publications Response' model.

    Attributes:
        publications (List[str]): The model property of type List[str].
        user_id (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "publications": "publications",
        "user_id": "user_id",
    }

    _optionals = [
        "publications",
        "user_id",
    ]

    def __init__(
        self,
        publications=APIHelper.SKIP,
        user_id=APIHelper.SKIP):
        """Initialize a UserPublicationsResponse instance."""
        # Initialize members of the class
        if publications is not APIHelper.SKIP:
            self.publications = publications
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        publications =\
            dictionary.get("publications")\
            if dictionary.get("publications")\
                else APIHelper.SKIP
        user_id =\
            dictionary.get("user_id")\
            if dictionary.get("user_id")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(publications,
                   user_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _publications=(
            self.publications
            if hasattr(self, "publications")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"publications={_publications!r}, "
            f"user_id={_user_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _publications=(
            self.publications
            if hasattr(self, "publications")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"publications={_publications!s}, "
            f"user_id={_user_id!s}, "
            f")"
        )
