"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class UserListsResponse(object):
    """Implementation of the 'User Lists Response' model.

    Attributes:
        lists (List[str]): The model property of type List[str].
        user_id (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lists": "lists",
        "user_id": "user_id",
    }

    _optionals = [
        "lists",
        "user_id",
    ]

    def __init__(
        self,
        lists=APIHelper.SKIP,
        user_id=APIHelper.SKIP):
        """Initialize a UserListsResponse instance."""
        # Initialize members of the class
        if lists is not APIHelper.SKIP:
            self.lists = lists
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        lists =\
            dictionary.get("lists")\
            if dictionary.get("lists")\
                else APIHelper.SKIP
        user_id =\
            dictionary.get("user_id")\
            if dictionary.get("user_id")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(lists,
                   user_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _lists=(
            self.lists
            if hasattr(self, "lists")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"lists={_lists!r}, "
            f"user_id={_user_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _lists=(
            self.lists
            if hasattr(self, "lists")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"lists={_lists!s}, "
            f"user_id={_user_id!s}, "
            f")"
        )
