"""mediumapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from mediumapi.api_helper import APIHelper


class UserTopArticlesResponse(object):
    """Implementation of the 'User Top Articles Response' model.

    Attributes:
        associated_articles (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "associated_articles": "associated_articles",
    }

    _optionals = [
        "associated_articles",
    ]

    def __init__(
        self,
        associated_articles=APIHelper.SKIP):
        """Initialize a UserTopArticlesResponse instance."""
        # Initialize members of the class
        if associated_articles is not APIHelper.SKIP:
            self.associated_articles = associated_articles

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        associated_articles =\
            dictionary.get("associated_articles")\
            if dictionary.get("associated_articles")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(associated_articles)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _associated_articles=(
            self.associated_articles
            if hasattr(self, "associated_articles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"associated_articles={_associated_articles!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _associated_articles=(
            self.associated_articles
            if hasattr(self, "associated_articles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"associated_articles={_associated_articles!s}, "
            f")"
        )
